# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
#!pip install mdutils

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

1.22.3


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
A = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
A.size

10

In [7]:
A.itemsize

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
A = np.zeros(10)
A[0] = 1
print(A)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
list(reversed(A))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
a = [1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
np.random.random((3,3,3))

array([[[0.4936267 , 0.50196006, 0.62837846],
        [0.62976542, 0.64391192, 0.8793343 ],
        [0.99009848, 0.09060259, 0.20014533]],

       [[0.80905278, 0.73303372, 0.19642549],
        [0.37326783, 0.41959686, 0.25398261],
        [0.66272251, 0.00681178, 0.17844219]],

       [[0.14663647, 0.42668811, 0.69442854],
        [0.76867302, 0.60924031, 0.71249879],
        [0.38951824, 0.04044458, 0.22364463]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
s = np.random.random((10,10))
print(s)
print("min: ", s.min(), "  max: ", s.max())

[[0.91674133 0.35442115 0.85106687 0.75589973 0.05249042 0.57173397
  0.97452373 0.05472166 0.82117411 0.19934208]
 [0.78065741 0.81102223 0.13757882 0.60652228 0.79830019 0.87216771
  0.70741701 0.80074083 0.29793725 0.65736193]
 [0.97067364 0.51076845 0.7068336  0.68228427 0.23723334 0.65785153
  0.44409966 0.16175808 0.3509922  0.45767407]
 [0.69567202 0.10704039 0.15889549 0.89268388 0.27266862 0.41352161
  0.95401906 0.37810461 0.41365905 0.97011619]
 [0.10051243 0.43584254 0.19811091 0.9758051  0.15690127 0.8135895
  0.21077372 0.49031946 0.89535232 0.33587698]
 [0.11518573 0.03847695 0.64224548 0.89590702 0.20748857 0.52419012
  0.43120211 0.24031896 0.38473861 0.41298308]
 [0.93017924 0.56404052 0.71456933 0.35687505 0.95147454 0.1008678
  0.55734904 0.99542739 0.19852682 0.94463589]
 [0.89034211 0.58959846 0.34643941 0.07787278 0.30075925 0.97125973
  0.8727139  0.46101014 0.12496434 0.10559878]
 [0.97657828 0.90175214 0.9230427  0.72360963 0.46622716 0.64416296
  0.11112382 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
d = np.random.random(30)
print(d)
d.mean()

[0.30339165 0.71296985 0.63418235 0.49546973 0.95492274 0.86560589
 0.29178199 0.76336746 0.75431868 0.24460953 0.41286524 0.78531281
 0.24575264 0.29220402 0.52845433 0.76572695 0.61487627 0.85573723
 0.7086499  0.37525143 0.2455317  0.32889639 0.39617765 0.04732056
 0.46227228 0.78874868 0.50128727 0.58634635 0.43621614 0.55832   ]


0.5318855898087416

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
q = np.ones((5,5))
q[1:-1, 1:-1] = 0
q

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
q = np.ones((6,6))
s = np.pad(q, 1, 'constant', constant_values=0)
s

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.info(np.pad)

 pad(array, pad_width, mode='constant', **kwargs)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
  

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

1) nan + 
2) true -
3) false +
4) false -
5) false -
6) true -

In [21]:
print("Правильные ответы:")
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

Правильные ответы:
nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
x = np.diag((1,2,3,4), k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [23]:
n = np.indices((8,8)).sum(axis=0) % 2
n

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

In [24]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [25]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [26]:
a = np.array([[0,1],[1,0]])
np.tile(a, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [27]:
w = np.random.rand(5,5)
norm = (w - np.mean(w))/np.std(w)
print(w)
print(norm)

[[0.10513264 0.41546063 0.09522726 0.77723201 0.63547099]
 [0.85492634 0.98007401 0.5093532  0.46078363 0.81946081]
 [0.0533505  0.77036677 0.5775979  0.06644478 0.39483984]
 [0.73039107 0.38731605 0.73729864 0.6155296  0.17936982]
 [0.8514677  0.3727101  0.72723465 0.41719201 0.80218224]]
[[-1.57044606 -0.43263101 -1.60676404  0.89380083  0.37403521]
 [ 1.17866644  1.63751937 -0.08837466 -0.2664546   1.04863237]
 [-1.76030483  0.86862948  0.16184398 -1.71229477 -0.50823697]
 [ 0.72205889 -0.53582286  0.74738545  0.30092025 -1.29825602]
 [ 1.16598536 -0.58937546  0.71048592 -0.42628289  0.98528065]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [28]:
color = np.dtype([("R", np.ubyte), ("G", np.ubyte), ("B", np.ubyte), ("A", np.ubyte)])

In [29]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [30]:
a = np.ones((5, 3))
b = np.ones((3, 2))
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
a @ b

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [32]:
a = np.arange(15)
a[(3 < a)&(a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

1) 0 + 1 + 2 + 3 + 4 - 1 = 9    # sum(iterable, start=0)


2) 0 + 1 + 2 + 3 + 4 = 10    # numpy.sum(a, axis=None, dtype=None, out=None, ...)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [33]:
z = [1,2,3,4,5]

In [34]:
z<z>z

False

 - Z**Z (-)
 - 2 << Z >> 2 (-)
 - Z <- Z (-)
 - 1j*Z (-)
 - Z/1/1 (-)
 - Z < Z > Z (+)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [35]:
np.array(0) / np.array(0)

<ipython-input-35-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [36]:
np.array(0) // np.array(0)

<ipython-input-36-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [37]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [38]:
np.info(np.copysign)

copysign(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Change the sign of x1 to that of x2, element-wise.

If `x2` is a scalar, its sign will be copied to all elements of `x1`.

Parameters
----------
x1 : array_like
    Values to change the sign of.
x2 : array_like
    The sign of `x2` is copied to `x1`.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the uf

In [39]:
Z = np.random.uniform(-10,+10,10)
Z

array([ 6.25064755,  9.86413285, -3.69101901, -3.79732474,  3.36609971,
        1.92696429, -8.05425803, -6.77566812, -3.25599762, -4.07998426])

In [40]:
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 7. 10. -4. -4.  4.  2. -9. -7. -4. -5.]


In [41]:
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 7. 10. -4. -4.  4.  2. -9. -7. -4. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [42]:
a = np.random.randint(10, size=10)
b = np.random.randint(10, size=10)
print(a)
print(b)

[3 4 0 7 9 7 9 9 9 3]
[1 3 6 4 3 9 2 0 4 7]


In [43]:
np.intersect1d(a, b)


array([0, 3, 4, 7, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [44]:
Z = np.ones(1) / 0

<ipython-input-44-915f24c547f4>:1: RuntimeWarning: divide by zero encountered in true_divide
  Z = np.ones(1) / 0


In [45]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [46]:
# Back to normal
_ = np.seterr(**defaults)

In [47]:
# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-48-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [49]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [50]:
np.datetime64.__doc__

"If created from a 64-bit integer, it represents an offset from\n    ``1970-01-01T00:00:00``.\n    If created from string, the string can be in ISO 8601 date\n    or datetime format.\n\n    >>> np.datetime64(10, 'Y')\n    numpy.datetime64('1980')\n    >>> np.datetime64('1980', 'Y')\n    numpy.datetime64('1980')\n    >>> np.datetime64(10, 'D')\n    numpy.datetime64('1970-01-11')\n\n    See :ref:`arrays.datetime` for more information.\n\n    :Character code: ``'M'``"

In [51]:
print("yesterday", yesterday)
print("today", today)
print("tomorrow", tomorrow)

yesterday 2022-09-27
today 2022-09-28
tomorrow 2022-09-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [52]:
np.arange('2016-07', '2016-08' , dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [53]:
np.multiply(np.add(a, b), np.divide(np.negative(a), 2))

array([ -6. , -14. ,   0. , -38.5, -54. , -56. , -49.5, -40.5, -58.5,
       -15. ])

In [54]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [55]:
array = np.random.uniform(0, 10, 30)
array

array([9.79974792, 8.61116367, 4.86711086, 8.6460567 , 1.69424063,
       0.24722911, 0.68008357, 1.06156984, 9.77368008, 4.09408047,
       6.315023  , 3.11035172, 4.09844819, 5.84257132, 1.08217736,
       4.68018073, 4.90938731, 4.42042818, 7.1016273 , 0.61304484,
       7.97610532, 7.50169166, 0.81541509, 0.45148699, 2.3391935 ,
       6.01949075, 3.01837895, 9.24990422, 9.62463047, 9.21415635])

In [56]:
np.array([int(i) for i in array])

array([9, 8, 4, 8, 1, 0, 0, 1, 9, 4, 6, 3, 4, 5, 1, 4, 4, 4, 7, 0, 7, 7,
       0, 0, 2, 6, 3, 9, 9, 9])

In [57]:
array.astype(int)

array([9, 8, 4, 8, 1, 0, 0, 1, 9, 4, 6, 3, 4, 5, 1, 4, 4, 4, 7, 0, 7, 7,
       0, 0, 2, 6, 3, 9, 9, 9])

In [58]:
array // 1

array([9., 8., 4., 8., 1., 0., 0., 1., 9., 4., 6., 3., 4., 5., 1., 4., 4.,
       4., 7., 0., 7., 7., 0., 0., 2., 6., 3., 9., 9., 9.])

In [59]:
np.trunc(array)

array([9., 8., 4., 8., 1., 0., 0., 1., 9., 4., 6., 3., 4., 5., 1., 4., 4.,
       4., 7., 0., 7., 7., 0., 0., 2., 6., 3., 9., 9., 9.])

In [60]:
array - array % 1

array([9., 8., 4., 8., 1., 0., 0., 1., 9., 4., 6., 3., 4., 5., 1., 4., 4.,
       4., 7., 0., 7., 7., 0., 0., 2., 6., 3., 9., 9., 9.])

In [61]:
np.floor(array)

array([9., 8., 4., 8., 1., 0., 0., 1., 9., 4., 6., 3., 4., 5., 1., 4., 4.,
       4., 7., 0., 7., 7., 0., 0., 2., 6., 3., 9., 9., 9.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [62]:
n = np.zeros((5, 5))
for i in range(0, 5):
    for j in range(0, 5):
        n[j][i] = i
n

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [63]:
np.tile([0, 1, 2, 3, 4], (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [64]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
def generate():
    for i in range (10):
        yield i

g = generate()
np.fromiter(g, dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [66]:
np.linspace(0, 1, num=11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [71]:
array = np.random.uniform(0, 10, 10)
print(array)
array = np.sort(array, axis=-1, kind="quicksort")
print(array)

[7.14756081 5.29205329 9.51875258 2.38361678 5.38721244 6.73567325
 6.10637695 1.51911479 7.38358037 5.44266152]
[1.51911479 2.38361678 5.29205329 5.38721244 5.44266152 6.10637695
 6.73567325 7.14756081 7.38358037 9.51875258]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [74]:
arr = np.add.reduce(array)
arr

56.91660278283273

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)